language: cpp
dist: xenial

compiler:
  - gcc
  - clang
os:
  - linux
  - osx

matrix:
  exclude:
    # GCC fails on recent Travis OSX images.
    - compiler: gcc
      os: osx

script: python test/run.py
