name: unittest
on:
  push:
    paths-ignore:
    - 'docs/**'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: make test
      run: make test

  mac_tsan:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: make test_tsan
      run: make test_tsan

  mac_tsan_openssl:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: install openssl
      run: brew install openssl
    - name: make test
      run: make test_tsan_openssl

  mac_tsan_mbedtls:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: install mbedtls
      run: brew install mbedtls
    - name: make test
      run: make test_tsan_mbedtls

  win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
    - run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=cl.exe -DUSE_WS=1 -DUSE_TEST=1 ..
    - run: cmake --build build

    # Running the unittest does not work
    #- run: ../build/test/ixwebsocket_unittest.exe
    # working-directory: test
