name: unittest
on:
  push:
    paths-ignore:
    - 'docs/**'

jobs:
  windows_mbedtls:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
    - run: |
        vcpkg install zlib:x64-windows
    - run: |
        vcpkg install mbedtls:x64-windows
    - run: |
        vcpkg install spdlog:x64-windows
    - run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_COMPILER=cl.exe -DUSE_MBED_TLS=1 -DUSE_TLS=1 -DUSE_WS=1 -DUSE_TEST=1 ..
    - run: cmake --build build
